image: eosio/history-tools:demo-theia2

ports:
- port: 3000, 8888
- port: 9876
  onopen: ignore

tasks:
- command: cleos wallet unlock --password </password
- command: mkdir -p ~/eosio/chain && nodeos --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin
